language: node_js
node_js:
   - "0.10" # from 2013-03 maintenance till 2016-10
   - "0.12" # from 2015-02 maintenance till 2017-04
   - "4"  # LTS from 2015-10  maintenance till 2018-04
   - "6"  # LTS from 2016-10  maintenance till 2019-04
after_success:
   - COVERALLS_SERVICE_NAME=travis-ci COVERALLS_REPO_TOKEN=bOsNVcF2rXYY25lOxz8TqnyWCOSRqfdGD node_modules/.bin/builder test --coveralls
